# Separating Weeks

## Import Packages

In [206]:
# data analysis and wrangling
import pandas as pd
import numpy as np

# visualization
%matplotlib inline
import matplotlib.pyplot as plt

# wrangling os
import os

#date
from datetime import datetime

## Load Data

In [207]:
# Selecting course name
'''
   - gestion-organizaciones-efectivas / 7
   - camino-excelencia-gestion-proyectos / 5
   - gestion-empresarial-pyme / 5
   - aprendiendo-programar-python / 6
   - electrones-en-accion / 4
   - web-semantica / 7
   - aula-constructivista / 10
'''
course_name = 'gestion-organizaciones-efectivas'
number_weeks = 7

In [208]:
# Super Log
df = pd.read_csv('../data/super_log/' + course_name + '/coursera.csv', index_col='ucchile_user_id')

# Surveys
df_surveys_id = pd.read_csv('../data/surveys/' + course_name + '/users_id_lms.csv')
df_surveys = pd.read_csv('../data/surveys/' + course_name + '/NoteMyProgress_SRL.csv')

In [209]:
df.head(2)

,course_passing_state,course_passed_items,course_grade,week_1_lecture_MGxyO,week_1_ts_lecture_MGxyO,week_2_lecture_ecIap,week_2_ts_lecture_ecIap,week_2_lecture_kRuL0,week_2_ts_lecture_kRuL0,week_2_lecture_mbU0x,...,week_3_exam_qt6b6,week_3_ts_exam_qt6b6,week_4_exam_Xjkl6,week_4_ts_exam_Xjkl6,week_5_exam_IZTWl,week_5_ts_exam_IZTWl,week_6_exam_pqfoB,week_6_ts_exam_pqfoB,week_7_exam_sGm0g,week_7_ts_exam_sGm0g
ucchile_user_id,,,,,,,,,,,,,,,,,,,,,
8d06f9d3a715e77de97387d78ca079413445fb13,0.0,2.0,0.242857,2.0,2018-04-26 15:58:03.394,1.0,2018-04-26 17:10:15.627,1.0,2018-04-26 16:02:49.981,1.0,...,0.714286,2018-05-27 22:06:21.884,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ec167156d585f1eedd359566152282004e170016,2.0,6.0,0.977143,2.0,2016-01-27 13:45:56.481,2.0,2016-01-28 16:17:51.361,2.0,2016-01-28 14:41:07.306,2.0,...,1.000000,2016-02-22 03:54:55.266,0.0,2016-02-28 23:38:20.52,1.0,2016-03-06 21:44:54.858,1.0,2016-03-13 21:21:15.528,0.857143,2016-03-21 03:32:26.679

## Important Functions

In [210]:
def get_number_cat(cat):
    output = 0
    for i in list(df_super.columns):
        if cat in i:
            output += 1
    return int(output/2)

In [211]:
def get_cols_week_no_ts(week, cols=list(df.columns)):
    output = []
    for i in cols:
        if 'week_' + str(week) in i and 'ts' not in i:
            output.append(i)
    #output.append('course_passing_state')
    #output.append('course_passed_items')
    #output.append('course_grade')
    return output

In [212]:
# From: Generico/main.ipynb
def get_columns(columns, string):
    output = []
    for col in list(columns):
        if string in col:
            output.append(col)
    return output

In [213]:
def get_completed(row, category):
    output = 0
    for i in row[category]:
        if i == 2:
            output += 1
    return output

In [214]:
def get_grade(row):
    try:
        return np.mean(row)
    except:
        return 0

In [215]:
def get_min(row, ts):
    try:
        return min(list(filter(lambda v: v==v, row[ts])))
    except:
        return 0

In [216]:
def get_max(row, ts):
    try:
        return max(list(filter(lambda v: v==v, row[ts])))
    except:
        return 0

## Main

In [217]:
# Course Metadata
metadata = {'course_name': course_name, 
            'course_total_weeks': number_weeks, 
            'course_total_lectures': int(len(get_columns(df.columns, 'lecture'))/2), 
            'course_total_supplements': int(len(get_columns(df.columns, 'supplement'))/2), 
            'course_total_quiz': int(len(get_columns(df.columns, 'quiz'))/2), 
            'course_total_exams': int(len(get_columns(df.columns, 'exam'))/2), 
            'course_total_phased_peer': int(len(get_columns(df.columns, 'phased_peer'))/2)}

In [218]:
metadata

{'course_name': 'gestion-organizaciones-efectivas',
 'course_total_weeks': 7,
 'course_total_lectures': 42,
 'course_total_supplements': 7,
 'course_total_quiz': 0,
 'course_total_exams': 6,
 'course_total_phased_peer': 0}

In [219]:
# Adding Course Charactetistics
df['course_name'] = metadata['course_name']
df['course_total_weeks'] = metadata['course_total_weeks']

df['course_total_lectures'] = metadata['course_total_lectures']
df['course_total_supplements'] = metadata['course_total_supplements']
df['course_total_quiz'] = metadata['course_total_quiz']
df['course_total_exams'] = metadata['course_total_exams']
df['course_total_phased_peer'] = metadata['course_total_phased_peer']

df['course_passable_items'] = metadata['course_total_exams'] + metadata['course_total_phased_peer']

In [220]:
# Rename Columns
df.rename(columns={'course_passing_state_id': 'course_passing_state', 
                   'course_grade_verified_passed_items': 'course_passed_items', 
                   'course_grade_verified': 'course_grade'}, 
         inplace=True)

In [221]:
# Adding percentage_passed_items
df['course_percentage_passed_items'] = df['course_passed_items'] / df['course_passable_items']

In [222]:
df.head(2)

,course_passing_state,course_passed_items,course_grade,week_1_lecture_MGxyO,week_1_ts_lecture_MGxyO,week_2_lecture_ecIap,week_2_ts_lecture_ecIap,week_2_lecture_kRuL0,week_2_ts_lecture_kRuL0,week_2_lecture_mbU0x,...,week_7_ts_exam_sGm0g,course_name,course_total_weeks,course_total_lectures,course_total_supplements,course_total_quiz,course_total_exams,course_total_phased_peer,course_passable_items,course_percentage_passed_items
ucchile_user_id,,,,,,,,,,,,,,,,,,,,,
8d06f9d3a715e77de97387d78ca079413445fb13,0.0,2.0,0.242857,2.0,2018-04-26 15:58:03.394,1.0,2018-04-26 17:10:15.627,1.0,2018-04-26 16:02:49.981,1.0,...,NaN,gestion-organizaciones-efectivas,7,42,7,0,6,0,6,0.333333
ec167156d585f1eedd359566152282004e170016,2.0,6.0,0.977143,2.0,2016-01-27 13:45:56.481,2.0,2016-01-28 16:17:51.361,2.0,2016-01-28 14:41:07.306,2.0,...,2016-03-21 03:32:26.679,gestion-organizaciones-efectivas,7,42,7,0,6,0,6,1.000000

In [223]:
cols_actual = get_cols_week_no_ts(1)
supplements = get_columns(cols_actual, 'supplement')
len(supplements)

0

In [224]:
df_lectures = pd.DataFrame()
df_supplements = pd.DataFrame()
df_exams = pd.DataFrame()
df_quiz = pd.DataFrame()
df_phased_peer = pd.DataFrame()

for actual_week in range(1, metadata['course_total_weeks'] + 1):
    # Columns of the actual week
    cols_actual = get_cols_week_no_ts(actual_week)
    
    ### LECTURES INFO ###
    lectures = get_columns(cols_actual, 'lecture')
    df_lectures_aux = pd.DataFrame(index=df.index)
    
    for index, row in df[lectures].fillna(0).iterrows():
        df_lectures_aux.at[index, 'week_lectures_completed'] = list(row.values).count(2)
        df_lectures_aux.at[index, 'week_lectures_started'] = list(row.values).count(1)
        df_lectures_aux.at[index, 'week_lectures_no_interacted'] = list(row.values).count(0)
    df_lectures_aux['week_total_lectures'] = len(lectures)
    
    ### SUPPLEMENTS INFO ###
    supplements = get_columns(cols_actual, 'supplement')
    df_supplements_aux = pd.DataFrame(index=df.index)
    
    for index, row in df[supplements].fillna(0).iterrows():
        df_supplements_aux.at[index, 'week_supplements_completed'] = list(row.values).count(2)
        df_supplements_aux.at[index, 'week_supplements_started'] = list(row.values).count(1)
        df_supplements_aux.at[index, 'week_supplements_no_interacted'] = list(row.values).count(0)
    df_supplements_aux['week_total_supplements'] = len(supplements)
    
            
    ### EXAMS INFO ###
    exams = get_columns(cols_actual, 'exam')
    df_exams_aux = pd.DataFrame(index=df.index)
    for index, row in df[exams].fillna('NOT').iterrows():
        df_exams_aux.at[index, 'week_exams_no_interacted'] = list(row.values).count('NOT')
        interacted = [x for x in row.values if x != 'NOT']
        
        if len(interacted):
            df_exams_aux.at[index, 'week_exams_interacted'] = len(interacted)
            df_exams_aux.at[index, 'week_exams_grade'] = get_grade(interacted)
        
        else: # No interacted
            df_exams_aux.at[index, 'week_exams_interacted'] = 0
            df_exams_aux.at[index, 'week_exams_grade'] = 0
    df_exams_aux['week_total_exams'] = len(exams)
    
    ### QUIZ INFO ###
    quiz = get_columns(cols_actual, 'quiz')
    df_quiz_aux = pd.DataFrame(index=df.index)
    for index, row in df[quiz].fillna('NOT').iterrows():
        df_quiz_aux.at[index, 'week_quiz_no_interacted'] = list(row.values).count('NOT')
        interacted = [x for x in row.values if x != 'NOT']
        
        if len(interacted):
            df_quiz_aux.at[index, 'week_quiz_interacted'] = len(interacted)
            df_quiz_aux.at[index, 'week_quiz_grade'] = get_grade(interacted)
        
        else: # No interacted
            df_quiz_aux.at[index, 'week_quiz_interacted'] = 0
            df_quiz_aux.at[index, 'week_quiz_grade'] = 0   
    df_quiz_aux['week_total_quiz'] = len(quiz)
    
    ### PHASED PEER INFO ###
    phased_peer = get_columns(cols_actual, 'phased_peer')
    df_phased_peer_aux = pd.DataFrame(index=df.index)
    for index, row in df[phased_peer].fillna('NOT').iterrows():
        df_phased_peer_aux.at[index, 'week_phased_peer_no_interacted'] = list(row.values).count('NOT')
        interacted = [x for x in row.values if x != 'NOT']
        
        if len(interacted):
            df_phased_peer_aux.at[index, 'week_phased_peer_interacted'] = len(interacted)
            df_phased_peer_aux.at[index, 'week_phased_peer_grade'] = get_grade(interacted)
        
        else: # No interacted
            df_phased_peer_aux.at[index, 'week_phased_peer_interacted'] = 0
            df_phased_peer_aux.at[index, 'week_phased_peer_grade'] = 0   
    df_phased_peer_aux['week_phased_peer_quiz'] = len(phased_peer)

    
    # Actual week!
    df_lectures_aux['week_actual'] = actual_week
    df_supplements_aux['week_actual_s'] = actual_week
    df_exams_aux['week_actual_e'] = actual_week
    df_quiz_aux['week_actual_q'] = actual_week
    df_phased_peer_aux['week_actual_p'] = actual_week

    
    # Concatinig different weeks
    df_lectures = pd.concat([df_lectures, df_lectures_aux])
    df_supplements = pd.concat([df_supplements, df_supplements_aux])
    df_exams = pd.concat([df_exams, df_exams_aux])  
    df_quiz = pd.concat([df_quiz, df_quiz_aux])  
    df_phased_peer = pd.concat([df_phased_peer, df_phased_peer_aux])    
    
    
    # Free memory
    del df_lectures_aux
    del df_supplements_aux
    del df_exams_aux
    del df_quiz_aux
    del df_phased_peer_aux

In [225]:
# Lectures
df_lectures['week_lectures_interacted'] = df_lectures['week_lectures_completed'] + df_lectures['week_lectures_started']

df_lectures['week_percentage_lectures_completed'] = df_lectures['week_lectures_completed'] / df_lectures['week_total_lectures']
df_lectures['week_percentage_lectures_started'] = df_lectures['week_lectures_started'] / df_lectures['week_total_lectures']
df_lectures['week_percentage_lectures_no_interacted'] = df_lectures['week_lectures_no_interacted'] / df_lectures['week_total_lectures']
df_lectures['week_percentage_lectures_interacted'] = df_lectures['week_lectures_interacted'] / df_lectures['week_total_lectures']

df_lectures.fillna(0, inplace=True)

In [226]:
df_lectures.head(2)

,week_lectures_completed,week_lectures_started,week_lectures_no_interacted,week_total_lectures,week_actual,week_lectures_interacted,week_percentage_lectures_completed,week_percentage_lectures_started,week_percentage_lectures_no_interacted,week_percentage_lectures_interacted
ucchile_user_id,,,,,,,,,,
8d06f9d3a715e77de97387d78ca079413445fb13,1.0,0.0,0.0,1,1,1.0,1.0,0.0,0.0,1.0
ec167156d585f1eedd359566152282004e170016,1.0,0.0,0.0,1,1,1.0,1.0,0.0,0.0,1.0

In [227]:
# Supplements
df_supplements['week_supplements_interacted'] = df_supplements['week_supplements_completed'] + df_supplements['week_supplements_started']

# if df_supplements['week_total_supplements'].iloc[1]:
df_supplements['week_percentage_supplements_completed'] = df_supplements['week_supplements_completed'] / df_supplements['week_total_supplements']
df_supplements['week_percentage_supplements_started'] = df_supplements['week_supplements_started'] / df_supplements['week_total_supplements']
df_supplements['week_percentage_supplements_no_interacted'] = df_supplements['week_supplements_no_interacted'] / df_supplements['week_total_supplements']
df_supplements['week_percentage_supplements_interacted'] = df_supplements['week_supplements_interacted'] / df_supplements['week_total_supplements']
# else:
#     df_supplements['week_percentage_supplements_completed'] = 0
#     df_supplements['week_percentage_supplements_started'] = 0
#     df_supplements['week_percentage_supplements_no_interacted'] = 0
#     df_supplements['week_percentage_supplements_interacted'] = 0
df_supplements.fillna(0, inplace=True)

In [228]:
df_supplements.head(2)

,week_supplements_completed,week_supplements_started,week_supplements_no_interacted,week_total_supplements,week_actual_s,week_supplements_interacted,week_percentage_supplements_completed,week_percentage_supplements_started,week_percentage_supplements_no_interacted,week_percentage_supplements_interacted
ucchile_user_id,,,,,,,,,,
8d06f9d3a715e77de97387d78ca079413445fb13,0.0,0.0,0.0,0,1,0.0,0.0,0.0,0.0,0.0
ec167156d585f1eedd359566152282004e170016,0.0,0.0,0.0,0,1,0.0,0.0,0.0,0.0,0.0

In [229]:
# Exams
df_exams['week_percentage_exams_interacted'] = df_exams['week_exams_interacted'] / df_exams['week_total_exams']
df_exams['week_percentage_exams_no_interacted'] = df_exams['week_exams_no_interacted'] / df_exams['week_total_exams']

df_exams.fillna(0, inplace=True)

In [230]:
df_exams.head(2)

,week_exams_no_interacted,week_exams_interacted,week_exams_grade,week_total_exams,week_actual_e,week_percentage_exams_interacted,week_percentage_exams_no_interacted
ucchile_user_id,,,,,,,
8d06f9d3a715e77de97387d78ca079413445fb13,0.0,0.0,0.0,0,1,0.0,0.0
ec167156d585f1eedd359566152282004e170016,0.0,0.0,0.0,0,1,0.0,0.0

In [231]:
df_supplements.loc['0009c2e89cf81209fc904abc95ed28bc24177f88']

,week_supplements_completed,week_supplements_started,week_supplements_no_interacted,week_total_supplements,week_actual_s,week_supplements_interacted,week_percentage_supplements_completed,week_percentage_supplements_started,week_percentage_supplements_no_interacted,week_percentage_supplements_interacted
ucchile_user_id,,,,,,,,,,
0009c2e89cf81209fc904abc95ed28bc24177f88,0.0,0.0,0.0,0,1,0.0,0.0,0.0,0.0,0.0
0009c2e89cf81209fc904abc95ed28bc24177f88,0.0,0.0,2.0,2,2,0.0,0.0,0.0,1.0,0.0
0009c2e89cf81209fc904abc95ed28bc24177f88,0.0,0.0,1.0,1,3,0.0,0.0,0.0,1.0,0.0
0009c2e89cf81209fc904abc95ed28bc24177f88,0.0,0.0,1.0,1,4,0.0,0.0,0.0,1.0,0.0
0009c2e89cf81209fc904abc95ed28bc24177f88,0.0,0.0,1.0,1,5,0.0,0.0,0.0,1.0,0.0
0009c2e89cf81209fc904abc95ed28bc24177f88,0.0,0.0,1.0,1,6,0.0,0.0,0.0,1.0,0.0
0009c2e89cf81209fc904abc95ed28bc24177f88,0.0,0.0,1.0,1,7,0.0,0.0,0.0,1.0,0.0

## Creating Final Log

In [232]:
cols = [
        'course_name', 
        'course_total_weeks',
        'course_passing_state', 
        'course_passed_items', 
        'course_grade', 
        'course_total_lectures',
        'course_total_supplements',
        'course_total_quiz',
        'course_total_exams',
        'course_total_phased_peer',
        'course_passable_items',
        'course_percentage_passed_items',
       ]

In [233]:
df_final = df.loc[:,cols]
df_final.fillna(0, inplace=True)

In [234]:
df_final.reset_index(inplace=True)
df_lectures.reset_index(inplace=True)
df_supplements.reset_index(inplace=True)
df_exams.reset_index(inplace=True)

In [235]:
# Adding Lectures info
df_final = df_final.merge(df_lectures, left_on='ucchile_user_id', right_on='ucchile_user_id', how='outer', copy=False)


# Adding Supplements info
df_final = df_final.merge(df_supplements, left_on=['ucchile_user_id', 'week_actual'], right_on=['ucchile_user_id', 'week_actual_s'], how='outer', copy=False)

# Adding Exams info
df_final = df_final.merge(df_exams, left_on=['ucchile_user_id', 'week_actual'], right_on=['ucchile_user_id', 'week_actual_e'], how='outer', copy=False)

# Adding Quiz info
df_final = df_final.merge(df_quiz, left_on=['ucchile_user_id', 'week_actual'], right_on=['ucchile_user_id', 'week_actual_q'], how='outer', copy=False)

# Adding Exams info
df_final = df_final.merge(df_phased_peer, left_on=['ucchile_user_id', 'week_actual'], right_on=['ucchile_user_id', 'week_actual_p'], how='outer', copy=False)

In [236]:
df_final.drop(columns=['week_actual_s', 'week_actual_e', 'week_actual_q', 'week_actual_p'], inplace=True)

In [237]:
df_final.head(3)

,ucchile_user_id,course_name,course_total_weeks,course_passing_state,course_passed_items,course_grade,course_total_lectures,course_total_supplements,course_total_quiz,course_total_exams,...,week_percentage_exams_interacted,week_percentage_exams_no_interacted,week_quiz_no_interacted,week_quiz_interacted,week_quiz_grade,week_total_quiz,week_phased_peer_no_interacted,week_phased_peer_interacted,week_phased_peer_grade,week_phased_peer_quiz
0,8d06f9d3a715e77de97387d78ca079413445fb13,gestion-organizaciones-efectivas,7,0.0,2.0,0.242857,42,7,0,6,...,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0
1,8d06f9d3a715e77de97387d78ca079413445fb13,gestion-organizaciones-efectivas,7,0.0,2.0,0.242857,42,7,0,6,...,1.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0
2,8d06f9d3a715e77de97387d78ca079413445fb13,gestion-organizaciones-efectivas,7,0.0,2.0,0.242857,42,7,0,6,...,1.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0

In [238]:
for col in df_final.columns:
    print(col)

ucchile_user_id
course_name
course_total_weeks
course_passing_state
course_passed_items
course_grade
course_total_lectures
course_total_supplements
course_total_quiz
course_total_exams
course_total_phased_peer
course_passable_items
course_percentage_passed_items
week_lectures_completed
week_lectures_started
week_lectures_no_interacted
week_total_lectures
week_actual
week_lectures_interacted
week_percentage_lectures_completed
week_percentage_lectures_started
week_percentage_lectures_no_interacted
week_percentage_lectures_interacted
week_supplements_completed
week_supplements_started
week_supplements_no_interacted
week_total_supplements
week_supplements_interacted
week_percentage_supplements_completed
week_percentage_supplements_started
week_percentage_supplements_no_interacted
week_percentage_supplements_interacted
week_exams_no_interacted
week_exams_interacted
week_exams_grade
week_total_exams
week_percentage_exams_interacted
week_percentage_exams_no_interacted
week_quiz_no_interacted
week_quiz_interacted
week_quiz_grade
week_total_quiz
week_phased_peer_no_interacted
week_phased_peer_interacted
week_phased_peer_grade
week_phased_peer_quiz

## Adding Survey Info

In [239]:
# Dropping unnecesary columns
cols_drop = ['respondent_id', 
             'collector_id', 
             'date_created', 
             'date_modified', 
             'ip_address', 
             'email_address', 
             'first_name', 
             'last_name', 
             'custom_1'] 
df_surveys.drop(columns=cols_drop, inplace=True)

# Dropping first row
df_surveys.drop(0, inplace=True)

In [240]:
# Delete email question:
for col in df_surveys.columns:
    if 'e-mail' in col:
        df_surveys.drop(columns= col, inplace=True)

In [241]:
df_surveys.set_index('user_id', inplace=True)

In [242]:
# Renaming Columns
# Creatin Dic
dic = {}
for index, col in enumerate(list(df_surveys.columns)):
        dic[col] = 'Q' + str(index + 1)

df_surveys.rename(columns=dic, inplace=True)

In [243]:
# Adding the correct id
df_surveys = df_surveys.merge(df_surveys_id, left_index=True, right_on='user_id_review', how='outer', copy=False).drop(columns=['user_id_review', 'user_email', 'user_ip'])

In [244]:
# Replacing values
vals_to_replace = {'Muy cierto para mÃ­': '5', 
                   'Bastante cierto para mÃ­': '4', 
                   'Algo cierto para mÃ­': '3', 
                   'Poco cierto para mÃ­': '2', 
                   'Nada cierto para mÃ­': '1', 
                   'Mi intenciÃ³n es completar todos los contenidos': '6', 
                   'Mi intenciÃ³n es completar parte de los contenidos': '7',                    
                   'Mi intenciÃ³n es completar todos los ejercicios': '8', 
                   'Mi intenciÃ³n es completar parte de los ejercicios': '9'}

In [245]:
df_surveys.replace(vals_to_replace, inplace=True)

In [246]:
df_surveys.head(2)

,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,...,Q19,Q20,Q21,Q22,Q23,Q24,Q25,Q26,Q27,user_id_lms
0,1,1,1,2,1,1,3,1,2,1,...,4,3,5,4,5,4,5,6,8,3a0b783ec71edfd76b7f129cf5436fc5838e74d4
1,3,5,3,3,3,3,4,4,2,4,...,5,5,5,2,5,2,3,6,8,0e11773e7c1a90a0f2ef4847c4f03a0186d7025a

In [247]:
## Merging to final log
df_final = df_final.reset_index().merge(df_surveys, left_on='ucchile_user_id', right_on='user_id_lms', how='outer', copy=False)

In [248]:
df_final.fillna(0, inplace=True)

In [249]:
df_final.drop(columns='user_id_lms', inplace=True)
df_final.set_index('ucchile_user_id', inplace=True)

In [253]:
len(df_final.columns)

73

## Export Data

In [251]:
# To super_log_week folder
#df.to_csv('../data/super_log_week/' + course_name + '.csv')